apiVersion: v1
kind: ConfigMap
metadata:
  name: payload-processing-plugins
data:
  extproc.yaml: |
    server:
      grpc_address: "0.0.0.0:9004"
      health_address: "0.0.0.0:50052"
      metrics_address: "0.0.0.0:9090"
      tls:
        mode: self_signed

    filter_chains:
      - name: ipp
        filters:
          - filter: headers
            request_add:
              - name: X-Praxis-Processed
                value: "true"
            response_set:
              - name: X-Praxis-Version
                value: "e2e"

    insecure_options:
      allow_unbounded_body: true
