apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - ../../../base
  - pre-processing-configmap.yaml
  - pre-processing-deployment.yaml
  - pre-processing-service.yaml

images:
  - name: praxis-extproc
    newName: praxis-extproc
    newTag: dev

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: payload-processing-plugins
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: payload-processing
