apiVersion: v1
kind: ConfigMap
metadata:
  name: payload-pre-processing-plugins
data:
  extproc.yaml: |
    server:
      grpc_address: "0.0.0.0:9004"
      health_address: "0.0.0.0:50052"
      metrics_address: "0.0.0.0:9090"
      tls:
        mode: self_signed

    filter_chains:
      - name: bbr
        filters:
          - filter: headers
            request_remove:
              - X-Gateway-Model-Name
          - filter: json_body
            request_extract:
              - pointer: /model
                header: X-Gateway-Model-Name
            on_invalid: continue

    insecure_options:
      allow_unbounded_body: true
